---
swagger: '2.0'
info:
  version: 3.0.0
  title: Honey API
  description: A Honey API for Honey webstore, the best store for buying honey based
    products.
  termsOfService: http://swagger.io/terms/
  contact:
    name: Rojberr
  license:
    name: MIT
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  "/catalog":
    get:
      description: Returns all Honey items from the system that the user has access to.
      produces:
        - application/json
      responses:
        '200':
          description: A list of Honey items.
          schema:
            type: array
            items:
              "$ref": "#/definitions/Honey"
  "/uploads":
    get:
      description: Returns ID, Content Type, filename and created at date for file
        with that ID.
      produces:
        - application/json
      responses:
        '200':
          description: A .json with file parameters. ID, Content Type, filename, date
            created at.
          schema:
            type: array
            items:
              "$ref": "#/definitions/Honey"
definitions:
  Honey:
    type: object
#    required:
#      - id
#      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
        example: Big jar
      price:
        type: integer
        example: 75.00
      amount:
        type: integer
        example: 75
      coverId:
        type: string
        example: null
